config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pics do 
  	member do 
  		put "like", to: "pics#upvote"
  	end
  end

  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
	acts_as_votable
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
	has_many :pics
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@pics = Pic.all.order("created_at DESC")
	end

	def show
	end

	def new
		@pic = current_user.pics.build
	end

	def create
		@pic = current_user.pics.build(pic_params)

		if @pic.save
			redirect_to @pic, notice: "Yes, it was posted!"
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @pic.update(pic_params)
			redirect_to @pic, notice: "Pic was updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@pic.destroy
		redirect_to root_path
	end

	def upvote
		@pic.upvote_by current_user
		redirect_to :back
	end

	private

	def pic_params
	 	params.require(:pic).permit(:title, :description, :image)
	end

	def find_pic
		@pic = Pic.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password_digest])
  		session[:user_id] = user.user_id
  		redirect_to root_url, notice: "Logged in!"
  	else
  		flash.now.alert = "Email or password is invalid"
  		render "new"
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password_digest)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagrams</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "Instagrams", root_path %>
        </div>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-left">
            <li>
              <%= link_to "Gram It", new_pic_path %>
            </li>
            <li>
              <%= link_to "Settings", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-left">
            <li>
              <%= link_to "Join", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Log In", new_user_session_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |name,msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pics/_form.html.erb
<%= simple_form_for @pic, html: { multipart: true} do |f| %>
  <% if @pic.errors.any? %>
    <div id="errors">
      <h2>
      	<%= pluralize(@pic.errors.count, "error") %>
      	prevented this Pic from saving
      </h2>
      <ul>
        <% @pic.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :image, input_html: { class:'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.input :title, input_html: { class:'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.input :description, input_html: { class:'form-control'} %>
  </div>

  	<%= f.button :submit, class: 'btn btn-info' %>

<% end %>

app/views/pics/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Pic</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <%= image_tag @pic.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pics/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="transitions-enabled" id="pics">
    <% @pics.each do |pic| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag pic.image.url(:medium)),pic %>
        <h2>
          <%= link_to pic.title, pic %>
        </h2>
      </div>
    <% end %>
  </div>
</div>

app/views/pics/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Post Pic</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pics/show.html.erb
<div class="row" id="pic_show">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel heading pic_image">
        <%= image_tag @pic.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pic.title %>
        </h1>
        <p>
          <%= @pic.description %>
        </p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">
              by
              <%= @pic.user.email %>
            </p>
          </div>
          <div class="col md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pic_path(@pic), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-thumbs-up"></span>
                <%= @pic.get_upvotes.size %>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_pic_path, class: "btn btn-info" %>
                <%= link_to "Delete", pic_path, method: :delete, data: { confirm: "Are You Sure?"}, class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>